#!/bin/bash
cat pillar/top_sls/_top.sls > pillar/top.sls && echo "" >> pillar/top.sls
find pillar/top_sls \( \( -type f -o -type l \) -not -name _top.sls -not -name '*.swp' \) -print0 | sort -z | xargs -i -0 bash -c "cat {} >> pillar/top.sls; echo "" >> pillar/top.sls"
