stages:
  - pull

.salt_master_pull:
  stage: pull
  only:
    refs:
      - master
  script:
    - sudo /srv/scripts/ci_sudo/salt_master_pull.sh

salt_master_pull_salt_master_1:
  extends: .salt_master_pull
  tags:
    - __SALT_MASTER_1_NAME__

salt_master_pull_salt_master_1:
  extends: .salt_master_pull
  tags:
    - __SALT_MASTER_2_NAME__
