stages:
  - pull
  - check
  - refresh
  - run_1
  - run_2
  - run_3
  - run_4
  - run_5

variables:
  GIT_SUBMODULE_STRATEGY: none

before_script:
  - . .pipeline-cache/gitlab.sh

.salt_master_pull:
  stage: pull
  only:
    refs:
      - master
  artifacts:
    paths:
      - .pipeline-cache
  script:
    # Clean everything but .pipeline-cache and keep it on next stages as artifact
    - clean_build_dir ".pipeline-cache"
    - sudo /srv/scripts/ci_sudo/salt_master_pull.sh

salt_master_pull_1:
  extends: .salt_master_pull
  tags:
    - __SALT_MASTER_1_NAME__

salt_master_pull_2:
  extends: .salt_master_pull
  tags:
    - __SALT_MASTER_2_NAME__

.count_alive_minions:
  stage: check
  only:
    refs:
      - /^run_.*/
    variables:
      # This var should be set on all job types, if removed - broken pipeline will run on tag creation
      - $SALT_MINION
  # Send collected alive_minions to next stage as artifacts also
  artifacts:
    paths:
      - alive_minions
      - .pipeline-cache
  # Do not fetch code from gitlab, it is not needed, we need only .pipeline-cache for scripts
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/count_alive_minions.sh

count_alive_minions_1:
  extends: .count_alive_minions
  tags:
    - __SALT_MASTER_1_NAME__

count_alive_minions_2:
  extends: .count_alive_minions
  tags:
    - __SALT_MASTER_2_NAME__

.refresh_pillar:
  stage: refresh
  only:
    refs:
      - /^run_.*/
    variables:
      - $SALT_MINION
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/refresh_pillar.sh

refresh_pillar_1:
  extends: .refresh_pillar
  tags:
    - __SALT_MASTER_1_NAME__

refresh_pillar_2:
  extends: .refresh_pillar
  tags:
    - __SALT_MASTER_2_NAME__

.salt_cmd:
  stage: run_1
  only:
    refs:
      - /^run_.*/
    variables:
      - $SALT_CMD
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    # Check at least one master has one needed minion
    - .pipeline-cache/check_alive_minions.sh
    # Run Salt Command
    - .pipeline-cache/salt_cmd.sh

salt_cmd_1:
  extends: .salt_cmd
  tags:
    - __SALT_MASTER_1_NAME__

salt_cmd_2:
  extends: .salt_cmd
  tags:
    - __SALT_MASTER_2_NAME__

.rsnapshot_backup_update_config:
  stage: run_1
  only:
    refs:
      - /^run_.*/
    variables:
      - $RSNAPSHOT_BACKUP_TYPE
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/rsnapshot_backup_update_config.sh

rsnapshot_backup_update_config_1:
  extends: .rsnapshot_backup_update_config
  tags:
    - __SALT_MASTER_1_NAME__

rsnapshot_backup_update_config_2:
  extends: .rsnapshot_backup_update_config
  tags:
    - __SALT_MASTER_2_NAME__

.rsnapshot_backup_sync:
  stage: run_2
  only:
    refs:
      - /^run_.*/
    variables:
      - $RSNAPSHOT_BACKUP_TYPE
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/rsnapshot_backup_sync.sh

rsnapshot_backup_sync_1:
  extends: .rsnapshot_backup_sync
  tags:
    - __SALT_MASTER_1_NAME__

rsnapshot_backup_sync_2:
  extends: .rsnapshot_backup_sync
  tags:
    - __SALT_MASTER_2_NAME__

.rsnapshot_backup_rotate:
  stage: run_3
  only:
    refs:
      - /^run_.*/
    variables:
      - $RSNAPSHOT_BACKUP_TYPE
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/rsnapshot_backup_rotate.sh

rsnapshot_backup_rotate_1:
  extends: .rsnapshot_backup_rotate
  tags:
    - __SALT_MASTER_1_NAME__

rsnapshot_backup_rotate_2:
  extends: .rsnapshot_backup_rotate
  tags:
    - __SALT_MASTER_2_NAME__

.rsnapshot_backup_check_backup:
  stage: run_4
  only:
    refs:
      - /^run_.*/
    variables:
      - $RSNAPSHOT_BACKUP_TYPE
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/rsnapshot_backup_check_backup.sh

rsnapshot_backup_check_backup_1:
  extends: .rsnapshot_backup_check_backup
  tags:
    - __SALT_MASTER_1_NAME__

rsnapshot_backup_check_backup_2:
  extends: .rsnapshot_backup_check_backup
  tags:
    - __SALT_MASTER_2_NAME__

.rsnapshot_backup_check_coverage:
  stage: run_5
  only:
    refs:
      - /^run_.*/
    variables:
      - $RSNAPSHOT_BACKUP_TYPE
  artifacts:
    paths:
      - .pipeline-cache
  variables:
    GIT_STRATEGY: none
  script:
    - .pipeline-cache/check_alive_minions.sh
    - .pipeline-cache/rsnapshot_backup_check_coverage.sh

rsnapshot_backup_check_coverage_1:
  extends: .rsnapshot_backup_check_coverage
  tags:
    - __SALT_MASTER_1_NAME__

rsnapshot_backup_check_coverage_2:
  extends: .rsnapshot_backup_check_coverage
  tags:
    - __SALT_MASTER_2_NAME__
